# Generated by Django 3.0.7 on 2020-06-22 08:20

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmline',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
