# Generated by Django 3.0.7 on 2020-06-22 10:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0002_auto_20200622_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='_geom_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True,
                                                            default=list, size=None),
        ),
    ]
