# Generated by Django 3.0.7 on 2020-06-23 07:03

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0003_layer__geom_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='_geom_types',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=10),
                                                                          blank=True, default=list,
                                                                          help_text='Leave this field empty. It is populated programmatically.',
                                                                          size=None),
        ),
        migrations.AlterField(
            model_name='layer',
            name='tags',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200),
                                                                          blank=True,
                                                                          help_text='Allowed formats: format key=val, key:valuefragment, key~regex, ~keyregex~regex, key=*, key',
                                                                          null=True, size=None),
        ),
    ]
