# Generated by Django 3.0.7 on 2020-06-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0004_auto_20200623_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='osmline',
            name='z_order',
            field=models.IntegerField(default=0),
        ),
    ]
