# Generated by Django 3.0.7 on 2020-06-26 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0006_auto_20200623_1058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layer',
            new_name='OsmLayer'
        )
    ]
