# Generated by Django 3.0.7 on 2020-06-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datahub', '0008_auto_20200626_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='OPTIONAL', max_length=1000, null=True)),
                ('version', models.CharField(blank=True, default='1.0.0',
                                             help_text='OPTIONAL. A semver.org style version number. When changes across tiles are introduced, the minor version MUST change.',
                                             max_length=10)),
                ('attribution', models.CharField(blank=True,
                                                 help_text='OPTIONAL. Contains an attribution to be displayed when the map is shown to a user. Implementations MAY decide to treat this as HTML or literal text',
                                                 max_length=200, null=True)),
                ('template', models.TextField(blank=True,
                                              help_text='OPTIONAL. Contains a mustache template to be used to format data from grids for interaction. See https://github.com/mapbox/utfgrid-spec/tree/master/1.2 for the interactivity specification.',
                                              max_length=1000, null=True)),
                ('legend', models.CharField(blank=True,
                                            help_text='OPTIONAL. Contains a legend to be displayed with the map. Implementations MAY decide to treat this as HTML or literal text.',
                                            max_length=200, null=True)),
                ('minzoom', models.IntegerField(blank=True, default=1, help_text='>= 0, <= 30.')),
                ('maxzoom', models.IntegerField(blank=True, default=30, help_text='>= 0, <= 30.')),
                ('default_zoom', models.IntegerField(blank=True, default=8, help_text='>= 0, <= 30.')),
            ],
        ),
        migrations.RemoveField(
            model_name='osmlayer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='osmlayer',
            name='name',
        ),
        migrations.CreateModel(
            name='Tileset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=50)),
                ('geom_type', models.CharField(max_length=10)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tilesets',
                                            to='datahub.Layer')),
            ],
        ),
        migrations.AddField(
            model_name='osmlayer',
            name='layer_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE,
                                       parent_link=True, primary_key=True, serialize=False, to='datahub.Layer'),
            preserve_default=False,
        ),
    ]
