# Generated by Django 3.0.7 on 2020-08-05 08:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0010_vectortilebasemap_wmtsbasemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='style',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
