version: '3.7'

services:
  web:
    build:
      context: ./osmserv
      dockerfile: Dockerfile.prod
    command: sh -c "celery -A osmserv worker -B -l info --concurrency=3 & gunicorn osmserv.wsgi:application --bind 0.0.0.0:8000 --timeout 300"
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - redis
    restart: unless-stopped

  redis:
    image: redis:5.0.8-alpine
    expose:
      - 6379

  db:
    image: kartoza/postgis:12.1
    volumes:
      - postgres_covid19_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER:-postgres}
      - POSTGRES_PASS=${SQL_PASSWORD:-postgres}
      - POSTGRES_DB=${SQL_DATABASE:-covid_db}
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      #- /etc/letsencrypt:/etc/letsencrypt # Path to letsencrypt folder
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_covid19_data_prod:
  static_volume: