version: '3.7'

services:
  web:
    build:
      context: aukigo
      dockerfile: Dockerfile.prod
    command: sh -c "celery -A aukigo worker -B -l info --concurrency=3 & gunicorn aukigo.wsgi:application --bind 0.0.0.0:8000 --timeout 300"
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - redis
    restart: unless-stopped

  redis:
    image: redis:5.0.8-alpine
    expose:
      - 6379

  pg_tileserv:
    # Conf file in /etc/pg_tileserv.toml, could be mounted if need to modify
    image: pramsey/pg_tileserv:20200612
    environment:
      - DATABASE_URL=postgresql://${SQL_USER:-postgres}:${SQL_PASSWORD:-postgres}@db/${SQL_DATABASE:-aukigo_db}
    depends_on:
      - db
    expose:
      - 7800
      # - 7801 #https
    restart:
      unless-stopped

  db:
    image: kartoza/postgis:12.1
    volumes:
      - postgres_covid19_data_prod:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER:-postgres}
      - POSTGRES_PASS=${SQL_PASSWORD:-postgres}
      - POSTGRES_DB=${SQL_DATABASE:-aukigo_db}
    restart: unless-stopped
    healthcheck:
      test: "exit 0"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      #- /etc/letsencrypt:/etc/letsencrypt # Path to letsencrypt folder
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_covid19_data_prod:
  static_volume:
